cc_binary(
    name = 'epoll_server',
    srcs = ['epoll_server.cc',
           ],
    deps = [],
    extra_cppflags = ['-std=c++11']
)

cc_binary(
    name = 'epoll_client',
    srcs = ['client.cc',
           ],
    deps = [],
    extra_cppflags = ['-std=c++11']
)
