cc_binary(
    name = 'shmwrite',
    srcs = ['shmwrite.cc',
           ],
    deps = [],
    extra_cppflags = [
    '-std=c++11',
    '-fpermissive']
)

cc_binary(
    name = 'shmread',
    srcs = ['shmread.cc',
           ],
    deps = [],
    extra_cppflags = [
    '-std=c++11',
    '-fpermissive']
)

cc_binary(
    name = 'socketpairmain',
    srcs = [
    'socketpairmain.cc',
    'CPC.cc'
    ],
    deps = [],
    extra_cppflags = [
    '-std=c++11',
    '-fpermissive']
)
